---
title: "flexdashboard Examples"
---

The examples below illustrate the use of flexdashboard with various packages and layouts. If you want to learn more about how the dashboards were created each example includes a link to it's source code. 

```{r setup, include=FALSE}
source("utils.R")
```


```{r, echo=FALSE}

showcaseThumbnails()

thumbnails(
  thumbnail(
    title = "Pokemon characters with highcharter",
    img = "images/highcharter-pokemon.png",
    href = "http://jkunst.com/flexdashboard-highcharter-examples/pokemon/"
  ),
  thumbnail(
    title = "Shiny: biclust example",
    img = "images/shiny-biclust.png",
    href = "https://jjallaire.shinyapps.io/shiny-biclust/"
  ),
  thumbnail(
    title = "Shiny: ggplot2 linked brushing",
    img = "images/shiny-ggplot2-brushing.png",
    href = "https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/"
  ),
  thumbnail(
    title = "Shiny: kmeans clustering",
    img = "images/shiny-dashboard.png",
    href = "https://jjallaire.shinyapps.io/shiny-kmeans/"
  ),
  thumbnail(
    title = "Sales report with highcharter",
    img = "images/highcharter.png",
    href = "https://beta.rstudioconnect.com/jjallaire/htmlwidgets-highcharter/"
  )
)
```

