---
title: "flexdashboard: Easy dashboard publishing for R"
---

<div id="main-banner" class="row">

<div class="col-sm-6">

* Use [R Markdown](http://rmarkdown.rstudio.com) to publish a group of related data visualizations as a dashboard.

* Flexible and easy to specify layouts, including the ability to have charts automatically resize to fill all available browser space.

* Works with base, lattice, and ggplot charts as well as interactive JavaScript visualizations based on [htmlwidgets](http://www.htmlwidgets.org).

* Optionally use [Shiny](http://shiny.rstudio.com) to drive visualizations dynamically.

</div>

</div>

## Examples


## Getting Started

Install the **flexdashboard** package from GitHub as follows:

```r
devtools::install_github("rstudio/flexdashboard")
```

To author a flexdashboard you create an R Markdown document with the `flexdashbaord::flex_dashboard` output format. The basic mechanics of creating and laying out a dashboard are described below. You can create your own custom layout from scratch or copy and modify one of the pre-canned ones from the [Layouts](layouts.html) page.

Once you've mastered the basics check out the [Advanced](advanced.html) page for documentation on themes, multi-page layouts, and including short text commentary within your dashboards. You can also optionally use [Shiny](shiny.html) to make your dashboards more dynamic and interactive.

## Dashbaord Layout

### Single Column

Dashboards are divided into columns and rows, where by default columns are defined using level 2 markdown headers (`------------------`) and charts are defined using level 3 headers (`###`). Charts are stacked vertically within a column. For example, this layout defines a single column with two charts:

    ---
    title: "My Dashboard"
    output: flexdashboard::flex_dashboard
    ---
    
    Column
    ------------------------------------------------
    
    ### Chart 1
    
    
    ### Chart 2

### Multiple Columns

To add a second column of charts we just add another column section:

    ---
    title: "My Dashboard"
    output: flexdashboard::flex_dashboard
    ---
    
    Column
    ------------------------------------------------
    
    ### Chart 1
    
    
    ### Chart 2
    
    
    Column
    ------------------------------------------------
    
    ### Chart 3
    
    
    ### Chart 4


### Row Orientation

The examples above use the default orientation of "columns", however it's also possible to layout a dashboard using a "rows" orientation. In this case rows are defined using level 2 markdown headers (`------------------`) and charts are defined using level 3 headers (`###`). Charts are stacked horizontally within a row. For example, this layout defines two rows, the first of which has a single chart and the second of which has two charts:

    ---
    title: "My Dashboard"
    output: 
      flexdashboard::flex_dashboard:
        orientation: rows
    ---
    
    Row
    ------------------------------------------------
    
    ### Chart 1
    
    
    Row
    ------------------------------------------------
    
    ### Chart 2
    
    
    ### Chart 3
    


### Filling the Page

Note that by default the charts flow down the page and the page scrolls if they occupy more space than is available. However, you might prefer that all charts be automatically sized to fill the containing web page. To do that you specify the fill_page option:

    ---
    title: "My Dashboard"
    output: 
      flexdashboard::flex_dashboard:
        fill_page: true
        orientation: rows
    ---
    
### Chart Sizing

By default charts also split space equally with other charts in their row or column. You may however wish to emphasize certain charts by allocating more space to them. The space allocated to a chart is determined by the knitr fig.width and fig.height options, which by default use a width of 5 inches and a height of 3.5 inches. If we wanted to allocate more vertical space to the single chart in the first row we could change it's fig.width and fig.height accordingly.

Here's a complete example that combines the fill_page option with a custom size for the chart in the first row:

    ---
    title: "My Dashboard"
    output: 
      flexdashboard::flex_dashboard:
        fill_page: true
        orientation: rows
    ---
    
    Row
    ------------------------------------------------
    
    ### Chart 1

<!---
    ```{r, fig.width=10, fig.height=7}
    library(dygraphs)
    dygraph(ldeaths)
    ```
--->

    Row
    ------------------------------------------------
    
    ### Chart 2
    
    
    ### Chart 3
    
Note that we've specified an explicit width and height for Chart 1 which is twice the default width and height. This results in a layout that more clearly emphasizes the first chart.

Also realize that because flexdashboard is doing some automatic layout to fill the browser's width and height, the figure sizes provided are approximate and best understood as relative sizes between charts in the same dashboard. 
Scaling 

Charts will always be automatically scaled to fit within their allocated region. For charts based on htmlwidgets (JavaScript) this scaling will nearly always result in a chart that perfectly fits the bounds of it's container. However, for charts based on standard R graphics the chart will be scaled so that it's original aspect ratio is preserved. Therefore, the closer the specified fig.width and fig.height are to the actual laid out size of the chart the better it will scale.


