---
title: "Deaths from Lung Cancer"
output: 
  flexdashboard::flex_dashboard: 
    devel: true
    self_contained: false
    fill_page: false
    theme: yeti
knit: flexdashboard:::knit2browser
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(d3heatmap)
library(leaflet)
library(dygraphs)
```

# Page 1

### Plotly

```{r, fig.width=8, fig.height=4}
p <- ggplot(data = diamonds, aes(x = cut, fill = clarity)) +
            geom_bar(position = "dodge")
ggplotly(p)
```

### Heatmap

```{r}
d3heatmap(mtcars, scale="column", colors="Blues")
```

### Leaflet

```{r}
leaflet() %>% addTiles()
```

### Dygraphs

```{r}
dygraph(ldeaths)
```




# Page 2

### Cars

```{r, fig.width=8, fig.height=4}
p <- ggplot(data = diamonds, aes(x = cut, fill = clarity)) +
            geom_bar(position = "dodge")
ggplotly(p)
```

### Heatmap

```{r}
d3heatmap(mtcars, scale="column", colors="Blues")
```

### Leaflet

```{r}
leaflet() %>% addTiles()
```

### Dygraphs

```{r}
dygraph(ldeaths)
```




