---
title: "Deaths from Lung Cancer"
output: 
  flexdashboard::flex_dashboard: 
    fill_page: true
    orientation: columns
    theme: default
runtime: shiny
---

```{r setup, include=FALSE}
library(dygraphs)
```

Inputs {.sidebar}
-------------------------------------------------------------------------------

```{r}
numericInput("months", label = "Months to Predict",
              value = 72, min = 12, max = 144, step = 12)

selectInput("interval", label = "Prediction Interval",
            choices = c("0.80", "0.90", "0.95", "0.99"),
            selected = "0.95")

checkboxInput("showgrid", label = "Show Grid", value = TRUE)
```

Outputs
-------------------------------------------------------------------------------

### Predicted Deaths/Month (dygraphs)

```{r}
predicted <- reactive({
  hw <- HoltWinters(ldeaths)
  predict(hw, n.ahead = input$months, prediction.interval = TRUE,
          level = as.numeric(input$interval))
})

renderDygraph({
  dygraph(predicted()) %>%     
    dySeries(c("lwr", "fit", "upr"), label = "Deaths") %>%
    dyOptions(drawGrid = input$showgrid)
})
```

### Predicted Deaths/Month (base)

```{r}
hw <- HoltWinters(ldeaths)
pred <- predict(hw, n.ahead = 72, prediction.interval = TRUE, level = 0.95)

dygraph(pred) %>%     
  dySeries(c("lwr", "fit", "upr"), label = "Deaths") %>%
  dyOptions(drawGrid = TRUE)
```

