---
title: "flexdashboard: Embedded Shiny Apps"
output: 
  flexdashboard::flex_dashboard:
    social: menu
    source_code: embed 
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Inline
=======================================================================

### Inline Shiny Application via shinyApp

```{r}
shinyApp(
  ui = fillPage(
    fillCol(flex = c(NA, 1), 
      inputPanel(
        selectInput("region", "Region:", choices = colnames(WorldPhones))
      ),
      plotOutput("phonePlot", height = "100%")
    )
  ),
  server = function(input, output) {
    output$phonePlot <- renderPlot({
      barplot(WorldPhones[,input$region]*1000, 
              ylab = "Number of Telephones", xlab = "Year")
    })
  },
  options = list(height = 500)
)
```

Module
=======================================================================

### Demonstration of Shiny Modules

```{r, include=FALSE}
# Shiny module definition (would typically be defined in a separate R script)

# input function
worldPhonesInput <- function(id) {
  ns <- NS(id)
  fillCol(height = 500, flex = c(NA, 1), 
    inputPanel(
      selectInput(ns("region"), "Region:", choices = colnames(WorldPhones))
    ),
    plotOutput(ns("phonePlot"), height = "100%")
  )
}

# output function
worldPhones <- function(input, output, session) {
  
  telephones <- reactive({
    WorldPhones[,input$region]*1000
  })
  
  output$phonePlot <- renderPlot({
    barplot(telephones(), 
            ylab = "Number of Telephones", xlab = "Year")
  })
  
  return(telephones)
}
```

```{r}
# Call the shiny module
callModule(worldPhones, "phones")
```

External
=======================================================================

### External Shiny Application via shinyAppDir

```{r}
shinyAppDir(
  system.file("examples/06_tabsets", package="shiny"),
  options = list(height=850)
)
```

