---
title: "ggplot2 Brushing"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny_prerendered
---

```{r, context="data", include=FALSE}
library(datasets)
mtcars2 <- mtcars[, c("mpg", "cyl", "wt")]
```


```{r, context="server"}
# Reactive that returns the whole dataset if there is no brush
selectedData <- reactive({
  data <- brushedPoints(mtcars2, input$plot1_brush)
  if (nrow(data) == 0)
    data <- mtcars2
  data
})
```

Column {data-width=650}
-----------------------------------------------------------------------

### Miles Per Gallon vs. Weight {data-width=600}

```{r}
library(ggplot2)
plotOutput("plot1", brush = brushOpts(id = "plot1_brush"))
```

```{r, context="server"}
output$plot1 <- renderPlot({
  ggplot(mtcars2, aes(wt, mpg)) + geom_point()
})
```


### Miles Per Gallon and Cylinders

```{r}
plotOutput("cylinders")
```

```{r, context="server"}
output$cylinders <- renderPlot({
  ggplot(selectedData(), aes(factor(cyl), mpg))  + geom_boxplot()
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Car Details {data-width=400}

```{r}
tableOutput("details")
```

```{r, context="server"}
output$details <- renderTable({
  selectedData()
})
```
