---
title: "Distribution Generator"
output: flexdashboard::flex_dashboard
runtime: shiny
---

Column {.sidebar}
-------------------------------------------------------------------------------

```{r}
radioButtons("dist", "Distribution type:",
                   c("Normal" = "norm",
                     "Uniform" = "unif",
                     "Log-normal" = "lnorm",
                     "Exponential" = "exp"))
      
sliderInput("n", 
            "Number of observations:", 
             value = 500,
             min = 1, 
             max = 1000)
```
                 
Column
-------------------------------------------------------------------------------

### Plot

```{r}
# Reactive expression to generate the requested distribution.
# This is called whenever the inputs change. The output
# functions defined below then all use the value computed from
# this expression
data <- reactive({
  dist <- switch(input$dist,
                 norm = rnorm,
                 unif = runif,
                 lnorm = rlnorm,
                 exp = rexp,
                 rnorm)
    
  dist(input$n)
})

# Generate a plot of the data. Also uses the inputs to build
# the plot label. Note that the dependencies on both the inputs
# and the data reactive expression are both tracked, and
# all expressions are called in the sequence implied by the
# dependency graph
renderPlot({
  dist <- input$dist
  n <- input$n
  
  hist(data(), 
       main=paste('r', dist, '(', n, ')', sep=''))
})
```

### Summary

```{r}
renderPrint({
  summary(data())
})
```


