on:
  push:
    branches:
      - main
      - master
      - rc-**
  pull_request:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and query dependencies
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
          restore-keys: ${{ runner.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          pak::local_system_requirements(execute = TRUE)
          pak::pkg_system_requirements("pkgdown", execute = TRUE)
        shell: Rscript {0}

      - name: Install package and dependencies
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
          pak::pkg_install("r-lib/pkgdown")
          pak::pkg_install("rstudio/quillt")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Build pkgdown site (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          pkgdown::build_site(new_process = FALSE)
      # Must validate after. Otherwise files are saved and `pkgdown::build_site()` gets mad
      - name: Validate all topics exist (PR)
        if: github.event_name != 'push'
        shell: Rscript {0}
        run: |
          pkgdown::build_reference_index()
          stopifnot(length(warnings()) == 0)

      - name: Build pkgdown site (push)
        if: github.event_name == 'push'
        run: pkgdown::build_site(new_process = FALSE)
        shell: Rscript {0}


      - name: Deploy to Netlify (push)
        if: github.event_name == 'push'
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        # NETLIFY_AUTH_TOKEN added in the repo's secrets
        with:
          publish-dir: 'reference'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.head_commit.message }} (${{ github.sha }})'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
